# Generated by Django 2.1.2 on 2019-03-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20190319_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretcode',
            name='date_time_created',
            field=models.DateTimeField(),
        ),
    ]
