# Generated by Django 2.1.2 on 2019-03-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20190319_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretcode',
            name='code',
            field=models.IntegerField(),
        ),
    ]
