# Generated by Django 2.1.2 on 2019-03-19 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190312_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Panel'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
